// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4zEeXklgR248Zqa0x3lFUfTiB7R4xS0',
    appId: '1:183582074214:web:56e4ba7213eae086fcd4a7',
    messagingSenderId: '183582074214',
    projectId: 'mainproject-865d6',
    authDomain: 'mainproject-865d6.firebaseapp.com',
    storageBucket: 'mainproject-865d6.appspot.com',
    measurementId: 'G-8MSBDM5QXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgg2YN4jNf_hpLdsph3X3i5uk82JX9slc',
    appId: '1:183582074214:android:35b097908bb6d920fcd4a7',
    messagingSenderId: '183582074214',
    projectId: 'mainproject-865d6',
    storageBucket: 'mainproject-865d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlGxxvkEbZ_sugf2jXgfPPd9X-CB5LRE',
    appId: '1:183582074214:ios:ac4f6af547972ed6fcd4a7',
    messagingSenderId: '183582074214',
    projectId: 'mainproject-865d6',
    storageBucket: 'mainproject-865d6.appspot.com',
    iosBundleId: 'com.example.mainProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnlGxxvkEbZ_sugf2jXgfPPd9X-CB5LRE',
    appId: '1:183582074214:ios:20f23ee183b7b8fdfcd4a7',
    messagingSenderId: '183582074214',
    projectId: 'mainproject-865d6',
    storageBucket: 'mainproject-865d6.appspot.com',
    iosBundleId: 'com.example.mainProject.RunnerTests',
  );
}
